version: '3.8'

services:
  app:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --chdir app/
    volumes:
      - static_volume:/app/app/templates/static
      - media_volume:/app/app/media
    expose:
      - 8000
    environment:
      - RECAPTCHA_PRIVATE_KEY=
      - RECAPTCHA_PUBLIC_KEY=
      - DB_ENGINE=
      - DB_USER=
      - DB_PASS=
      - DB_HOST=
      - DB_PORT=
      - DB_NAME=
      - SECRET_KEY=
    depends_on:
    - db
  db:
    image: mysql:8.0.21
    container_name: db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/app/templates/static
      - media_volume:/app/app/media
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  static_volume:
  media_volume:

